export enum SocketEvent {
  TEST = 'TEST',

  // Admin
  HEALTH_FACTOR_UNDER_THREADHOLD = 'HEALTH_FACTOR_UNDER_THREADHOLD',
  LOAN_DEFAULTED = 'LOAN_DEFAULTED',
  BORROW_P2POOL = 'BORROW_P2POOL',

  // User
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  LOAN_REPAID = 'LOAN_REPAID',
  LOAN_DEFAULTED_P2P = 'LOAN_DEFAULTED_P2P',
  LOAN_RENEGOTIATE = 'LOAN_RENEGOTIATE',
  SEND_LOAN_RENEGOTIATE = 'SEND_LOAN_RENEGOTIATE',
  LOAN_FORCECLOSE = 'LOAN_FORCECLOSE',
  P2POOL_REPAY = 'P2POOL_REPAY',
  P2POOL_FORCECLOSE = 'P2POOL_FORCECLOSE',
  BUNDLE_UNSEAL = 'BUNDLE_UNSEAL',
  BUNDLE_SEAL = 'BUNDLE_SEAL',
  BUNDLE_BURN = 'BUNDLE_BURN',
  BUNDLE_TRANSFER = 'BUNDLE_TRANSFER',
  BUNDLE_MINT = 'BUNDLE_MINT',
  BUNDLE_IMMUTABLE = 'BUNDLE_IMMUTABLE',
  BUNDLE_ADD_AND_REMOVE = 'BUNDLE_ADD_AND_REMOVE',
  START_STAKING = 'START_STAKING',
  WITHDRAW_STAKING = 'WITHDRAW_STAKING',
  CLAIM_STAKING = 'CLAIM_STAKING',
  START_VESTING = 'START_VESTING',
  CLAIM_REWARD = 'CLAIM_REWARD',
  REVOKE_OFFER = 'REVOKE_OFFER',

  P2POOL_DEPOSIT = 'P2POOL_DEPOSIT',
  P2POOL_WITHDRAW = 'P2POOL_WITHDRAW',
}
